on:
  pull_request:
name: api-db-test
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup docker
        working-directory: ./delivery-docker
        run: docker-compose up -d

      - name: cache infra vendor
        id: api-cache
        uses: actions/cache@v1
        with:
          path: ./deliver-infra/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: infra composer install
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./delivery-docker
        run: docker-compose run --rm api bash -c "cd ../packages/delivery-infra && composer install -n --prefer-dist"

      - name: domain unit test
        working-directory: ./delivery-docker
        run: docker-compose run --rm api bash -c "cd ../packages/delivery-infra && ./vendor/bin/phpunit --testdox"
